import styles from "@/styles/Home.module.css";
import { Inter } from "next/font/google";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export type TeamType = {
  _id: string;
  name: string;
  image: string;
  description: string;
};

type TeamPropsType = {
  teams: TeamType[];
};

export default function Home({ teams }: TeamPropsType) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.grid}>
        {teams.map((team) => {
          return (
            <Link href={{ pathname: `/products/${team._id}` }} className={styles.card} key={team._id}>
              <Link className={styles.info} href={`/team/${team._id}`}>
                <Image src="/info-button.svg" alt={team.name} width={20} height={20}></Image>
              </Link>
              <Image src={team.image} alt={team.name} width={80} height={80}></Image>
              <h2 className={inter.className}>
                {team.name} <span>-&gt;</span>
              </h2>
            </Link>
          );
        })}
      </div>
    </>
  );
}

Home.getInitialProps = async () => {
  const response = await fetch("https://api-products-dh-next.vercel.app/teams");
  const teams = await response.json();

  return {
    teams,
  };
};

// export const getStaticProps: GetStaticProps = async () => {
//   const response = await fetch("https://api-products-dh-next.vercel.app/teams");
//   const teams = await response.json();

//   return {
//     props: {
//       teams,
//     },
//   };
// };
